version: 2

sources:
  - name: snowflake_sample_data
    description: 'sample data uploading'
    database: snowflake_sample_data
    schema: TPCDS_SF10TCL
    tables:
      - name: store_sales
        description: 'Details about sales'
     

